redesign how we handle cleanup tasks in isletd

diff --git a/bin/isletd b/bin/isletd
--- a/bin/isletd
+++ b/bin/isletd
@@ -73,11 +73,12 @@ load_config(){
   if [[ -f "$CONFIG" ]]; then
     . "$CONFIG"
     module="$CONFIG_DIR/modules/${MODULE}.conf"
-    [[ -f "$LIBISLET" ]]    && . "$LIBISLET"    || logfile "Unable to open $LIBISLET"
-    [[ -f "$module" ]]      && . "$module"      || logfile "Unable to open $module"
-    [[ -f "$environment" ]] && . "$environment" || logfile "Unable to open $environment"
+    [[ -f "$LIBISLET" ]]    && . "$LIBISLET"     || logfile "Unable to open $LIBISLET"
+    [[ -f "$module" ]]      && . "$module"       || logfile "Unable to open $module"
+    [[ -f "$environment" ]] && . "$environment"  || logfile "Unable to open $environment"
+    export CONFIG LIBISLET
   else
-    logger -s -p local0.notice -t "isletd" "$0: $FUNCNAME: Unable to read $CONFIG"
+    logfile "$FUNCNAME: Unable to read $CONFIG"
     return 1
   fi
 }
@@ -132,6 +133,29 @@ cleanup_by_user(){
 }
 
 ###################################################
+# Execute module tasks
+# Globals:
+#   DEBUG  - Debugging option from configs
+# Arguments:
+#   module - Path to module script
+#   task   - Name of function to execute in module
+#   opt    - An option passed to function (optional)
+#   env    - Training environment config file
+# Returns:
+#   None
+###################################################
+
+execute_task(){
+  local module="$1"
+  local task="$2"
+  local option="$3"
+  local environment="$4"
+  "$module" "$task" "$opt" "$env"
+  rc="$?"
+  [[ "$DEBUG" == "yes" ]] && logfile "Executed $task with status code $rc"
+}
+
+###################################################
 # Daemonize, run indefinitely every 60 seconds
 # Globals:
 #   Many
@@ -145,7 +169,7 @@ main(){
   # We're a daemon, we don't end
   while true; do
     ## Global tasks
-    sleep $INTERVAL
+    sleep ${INTERVAL:-60} # Default to one minute
     # Remove users which are older than $DAYS days
     [[ "$DAYS" ]] && cleanup_by_user "$DAYS"
     ## Per config tasks
@@ -155,12 +179,12 @@ main(){
         # Obtain configurations
         load_config "$environment" || continue
         # Execute cleanup functions from module
+        MODULE="$INSTALL_DIR/modules/$MODULE"
         if [[ -x "$MODULE" ]]; then
-          MODULE="$INSTALL_DIR/modules/$MODULE"
-          # Remove containers with date older than $DAYS
-          [[ "$DAYS" ]]         && "$MODULE" cleanup_by_date "$DAYS" "$environment"
-          # Remove old port forward rules
-          [[ "$VIRTUAL_PORT" ]] && "$MODULE" cleanup_by_forward
+          # Execute module tasks here
+          echo
+        else
+          logfile "Error: $MODULE does not exist or is not executable, skipping module maintenance."
         fi
       fi
     done
