configure: test for docker version and debian family

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13,6 +13,7 @@ OK=0
 CRITICAL=1
 DEPENDS="bash cron make sshd docker sqlite3"
 MISSING=()
+DEBIAN=0
 NO="${Y}[${N}${RF}NO${N}${Y}]${N}"
 YES="${Y}[${N}${BF}YES${N}${Y}]${N}"
 BULLET="${Y}[${N}${BF}*${N}${Y}]${N}"
@@ -41,26 +42,48 @@ check_linux()
         fi
 }
 
+is_debian()
+{
+	test -f /etc/debian_version && DEBIAN=1
+}
+
 check_dependencies()
 {
 	local depends=$1
         echo -n "${BULLET} Checking $depends ... "
 
         if [[ "x$(which $depends 2>/dev/null)" == "x" ]] ; then
-                echo "$NO $depends not found"
+
+		[ "$depends" = "docker" ] && test $DEBIAN -eq 1 &&
+			echo -n "$NO $depends not found, try "  &&
+			notice "\`\`make install-docker''" 	||
+               		echo "$NO $depends not found"
+
 		MISSING+=("$depends")
+
         else
                 echo "$YES $depends found"
         fi
 }
 
+check_docker_version()
+{
+	if ! echo ${MISSING[@]} | grep -q docker; then
+        	echo -n "${BULLET} Checking docker version... "
+        	docker version | grep -q 'Server version: 1.3' && echo "$YES 1.3+ found"|| echo "$NO 1.3+ not found"
+	fi
+}
+
 check_arch
 check_linux
+is_debian
 
 for i in $DEPENDS
 do
 	check_dependencies $i
 done
+
+check_docker_version
 
 if [ ${#MISSING[@]} -gt 0 ];
 then
